InvoicingSystem/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using InvoicingSystem.Models;


namespace InvoicingSystem.Controllers
{
    public class PeopleController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Customers");
        }

        public ActionResult Customers()
        {
            IEnumerable<Person> readResult = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59141/api/people");

                var responseTask = client.GetAsync("people");
                responseTask.Wait();

                var result = responseTask.Result;
                if(result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<IList<Person>>();
                    readTask.Wait();

                    readResult = readTask.Result; 
                }
                else
                {
                    readResult = Enumerable.Empty<Person>();

                    ModelState.AddModelError(string.Empty, "Server error.");
                }

            }

            return View(readResult.OrderBy(x => x.LastName));
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Create(Person person)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:59141/api/People");

                var postTask = client.PostAsJsonAsync<Person>("people", person);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("Customers");
                }
            }

            ModelState.AddModelError(string.Empty, "Server error.");

            return View(person);
        }
    }
}

InvoicingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Parkings database", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Customers", "Customers", "People", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Parkings", "ParkingsList", "Parkings", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Invoices", "InvoicesList", "Invoices")</li>
                    
                </ul>
                <h3 class="user-greeting">Hello, @Html.DisplayName(InvoicingSystem.Models.Person.FindPersonById(1).FirstName)!</h3>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>